# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84b0745da1fd42bc24fbe21d23315809b0ac95a1ebd2f879c45491348c42536e459581f702d8c8b296e80f2b42e2a298e251148765b6bb3f079b0579ca115811

test:
  secret_key_base: 7d368d0d8d48bfac2468bf68b80ec7425607adf0a4839eee97752c7a2149875a4cb974b1de5be100ba90e2594dfc1d6ff1ef3525fd64780c0fc704f554bb9a2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
